### PR TITLE
Fix for unconventional PKs

### PR DESCRIPTION
**Pull request by jeremyharris**
refs: #29, #30

### CODE REVIEW

**Comment by jeremyharris** [comment]
ping @lordphnx 

Any chance you were able to test your codebase against these changes?

**Comment by lordphnx** [comment]
@jeremyharris thanks for reminding me! Just ran the tests in one of my codebases:
 - 4.0.1 ✅ 
- 4.0.2 🔴 
- dev-issue/29 ✅ 

So looks to be all good 😄

**Comment by jeremyharris** [comment]
Great, thanks for taking a look!

**Comment by jeremyharris** [comment]
@lordphnx Thanks again for the report and for spending so much of your time working through this bug with me! I appreciate it!

**Comment by lordphnx** [comment]
No worries, have enjoyed the process, and appreciate your patience with my newbie-ness in the entire bug/PR process 😄

**Pull request merged**
