### PR TITLE
Cake 4.x EntityTrait _properties changed to _fields

### PR DESCRIPTION
**Pull request by jason-horvath**
Been going through a tedious 3.x to 4.x upgrade, and came across this change.

The `EntityTrait::$_properties` has now become `EntityTrait::$_fields`

https://api.cakephp.org/3.8/source-class-Cake.Datasource.EntityTrait.html#29-34

https://github.com/cakephp/cakephp/blob/master/src/Datasource/EntityTrait.php#L37

My unit tests relying on lazy-loading appear to be passing now. Just thought I'd share to help everyone out.  :)

PS: I would pick a dev branch if I could.

### CODE REVIEW

**Comment by KainGNX** [comment]
Made a bunch of other cake 4.x changes for compatibility, right now there is just one phpunit warning. But all tests pass within.

`There was 1 warning:

1) JeremyHarris\LazyLoad\Test\TestCase\ORM\LazyLoadEntityTraitTest::testDontInterfereWithContain
Trying to set mock method "_lazyLoad" with onlyMethods, but it does not exist in class "JeremyHarris\LazyLoad\TestApp\Model\Table\ArticlesTable". Use addMethods() for methods that don't exist in the class.`

Other than that, it's all good.

**Comment by jason-horvath** [comment]
Fixed that unit test warning I mentioned earlier. All passing green now!

**Review by jeremyharris — APPROVED** [review]

**Comment by jeremyharris** [comment]
Thanks for the PR, much appreciated!

I'll get travis working again (it got turned off somehow) and tag this ASAP.

**Comment by jeremyharris** [comment]
@KainGNX released: https://github.com/jeremyharris/cakephp-lazyload/releases/tag/4.0.0

Thanks again for the legwork :)

**Comment by jason-horvath** [comment]
You're welcome! Glad I could help! :D

**Pull request merged**
